# Written by junying, 2019-04-10
#
# Simple usage with a mounted data directory:
# > docker build -t htdfservice .
# > docker images
# > docker run -it -p 26657:26657 -p 26656:26656 -v ~/.hsd:/root/.hsd -v ~/.hscli:/root/.hscli  htdfservice hsd init --chain-id testchain
# > docker run -it -p 26657:26657 -p 26656:26656 -v ~/.hsd:/root/.hsd -v ~/.hscli:/root/.hscli  htdfservice hsd start 
FROM alpine:latest

RUN apk add --update ca-certificates
COPY ../../build/* /usr/local/bin/

ENV CHAINID testchain
ENV PASSPHRASE 12345678
ENV BALANCE 10000000htdf

RUN hsd init --chain-id $CHAINID
RUN hsd add-genesis-account $(hscli accounts new $PASSPHRASE) $BALANCE
RUN hsd add-genesis-account $(hscli accounts new $PASSPHRASE) $BALANCE
RUN hscli config chain-id $CHAINID
RUN hscli config output json
RUN hscli config indent true
RUN hscli config trust-node true

EXPOSE 1317 26656 26657

# Run hsd by default, omit entrypoint to ease using container with hscli
CMD ["hsd"]
# ENTRYPOINT ["hsd"]
